export const COURSE_VIDEO_LIST = "COURSE_VIDEO_LIST";
export const VIDEO_SELECTION = "VIDEO_SELECTION";
export const VIDEO_COMPLETED = "VIDEO_COMPLETED";
export const COURSE_RATING = "COURSE_RATING";

// export const EMPLOYEE_REMOVED = "EMPLOYEE_REMOVED";
// export const EMPLOYEE_UPDATED = "EMPLOYEE_UPDATED";
